change to pnpm

diff --git a/.github/workflows/ci-prettier.yaml b/.github/workflows/ci-prettier.yaml
--- a/.github/workflows/ci-prettier.yaml
+++ b/.github/workflows/ci-prettier.yaml
@@ -13,15 +13,15 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Setup Node.js
-        uses: actions/setup-node@v3
+        uses: pnpm/action-setup@v2
         with:
-          node-version: 16
-          cache: 'npm'
-
-      - name: Install prettier
-        # We don't want to save prettier as a dependency, so we use --no-save
-        run: npm install --no-save prettier
+          version: 6.32.9
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '14'
+          cache: 'pnpm'
+      - run: pnpm install --frozen-lockfile
 
       - name: Run prettier
-        run: npm run format:ci || echo "::error::remember to run 'pnpm run format', and commit again'"
+        run: pnpm run format:ci || echo "::error::remember to run 'pnpm run format', and commit again'"
 
